- name: Install zfs packages
  package:
    name: 
      - zfs-dkms
      - zfsutils-linux
    state: present
 
- name: Start service zfs if not started
  service:
    name: zfs-zed
    enabled: yes
    state: started
 
 # need to manually import the zfs pools if moved from another system.
 # zpool import pool-name
 
 # then share pool
 # zfs set sharenfs=on pool-name

 
 
 
- name: start zfs-share
  service:
    name: "zfs-share"
    state: started
 
# tags:
#  - zfs
