- name: Install zfs packages
  package:
    name: 
      - zfs-dkms
      - zfsutils-linux
    state: present
 
- name: Start service zfs if not started
  service:
    name: zfs-zed
    enabled: yes
    state: started
 
 # need to import the zfs pool
 # and share via nfs
 
 
 
- name: start zfs-share
  service:
    name: "zfs-share"
    state: started
 
# tags:
#  - zfs
