- name: Install zfs packages
  package:
    name: 
      - zfs-dkms
      - zfsutils-linux
    state: present
 
- name: Start service zfs if not started
  service:
    name: zfs-zed
    enabled: yes
    state: started
 
  tags:
    - zfs
