 
  netplan_apply: True
  
  netplan_packages:
    - nplan
    - netplan.io
  
  - name: Install netplan
    apt:
      name: "{{ netplan_packages }}"
      state: present
    become: true
    register: result
    until: result is successful
   
 
 
 
 - name: Copy over interface config files
   copy:
    src: ~/ansible/roles/netplan-eth0/files/10-eth0.yaml
    dest: /etc/netplan/10-eth0.yaml
    owner: root
    group: root
    mode: '0644'
  register: interfaceconfigfiles
  notify: netplan generate config
   
  
- name: Restart service if files changed  
  service:
    name: networking
    enabled: yes
    state: restarted
  when: interfaceconfigfiles.changed
 
 

 
 
  tags:
    - eth0
