---
- name: Firewall
  hosts: gateway2
  remote_user: pete
  become: "True"
  become_method: sudo

  roles:
    - hosts
    - netdata
    - haveged
    - netplan-eth0
    - shorewall
    - ntp-server
