---
- name: Firewall
  hosts: rpi-mesh1
  remote_user: pete
  become: "True"
  become_method: sudo

  roles:
    - hosts
    - netdata
    - haveged
    - internet
    - etho
    - shorewall
    - ntp-server
