- name: Initial Setup
  ####################################
  #
  # ansible-playbook -u USER -k -K initial-setup.yml
  #
  ####################################
  
  #vars_prompt:
  #  - name: "ansible_ssh_pass"
  #    prompt: "root password for remote connection?"
  #    private: yes
  #remote_user: pete
  become: "True"
  become_method: sudo
  hosts: all
  tasks:
    - name: Create DevOps User
      user:
        name: devops
        state: present
    - name: Add devops to sudoers
      lineinfile:
        path: /etc/sudoers.d/devops
        line: "devops        ALL=(ALL)       NOPASSWD: ALL"
        state: present
        create: true
    - name: Set authorized key
      authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', '~/ansible/devops_id_rsa.pub') }}"
