---
- name: nas
  hosts: rpinas
  #remote_user: ubuntu
  #become: "True"
  #become_method: sudo

  vars:
    share_path: /mnt/nfsroot



  roles:
    - netdata
    - zfs
    - nfs
    - cleanup
    - haveged
   
  
