---
- name: nas
  hosts: rpinas
  remote_user: pete
  become: "True"
  become_method: sudo

  vars:
    share_path: /mnt/nfsroot



  roles:
    - netdata
    - zfs
    - nfs
    - cleanup
    - haveged
   
  handlers:
    - name: update nfs exports
      command: exportfs -a
      listen: update nfs
