---
- name: rpimesh 
  hosts: rpimesh
  remote_user: pete
  become: "True"
  become_method: sudo
  serial: 1
  

  
  roles:
    - hosts
    - netdata
    - haveged
    - wpa-adhoc
    - etho
    - bridge
  
    
   
  
