---
- name: Upgrade all hosts  
  hosts: rpimesh
  remote_user: pete
  become: "True"
  become_method: sudo

  
  tasks:
    - name: Upgrade Archlinux hosts
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == 'Archlinux'  
      
    - name: Upgrade Ubuntu and Raspbian hosts
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes
      when: ansible_distribution == 'Ubuntu' or  ansible_distribution == 'Raspbian'

    - name: Upgrade Ubuntu snaps
      command: snap refresh
      when: ansible_distribution == 'Ubuntu'  
      
      
