---
- name: Upgrade all hosts  
  hosts: all
  #remote_user: pete
  #become: "True"
  #become_method: sudo


  tasks:
  - name: Upgrade Archlinux hosts
    roles:
      - archupdates
    when: ansible_distribution == 'Archlinux'  
