- name: Install netdata packages
  package:
    name: 
      - netdata
    state: present
 
- name: Start service netdata if not started
  service:
    name: netdata
    enabled: yes
    state: started
 
  tags:
    - netdata
