# netplan configuration of Eth0 - static address for gateway device
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.0.2/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [192.168.0.1,192.168.0.1]
