- name: remove the unwanted Ubuntu rpi packages
  package:
    name:
      - cloud-init
    state: absent

- name: remove unwanted Ubuntu snap packages
  snap:
    name:
      - lxd
    state: absent
