- name: remove tvheadend snap package
  snap:
    name: tvheadend
    state: absent
    
- name: install tvheadend apt repository
  apt_repository:
    repo: ppa:mamarley/tvheadend-git-stable
    state: present
    update: yes
    
- name: install tvheadend
  package:
    name: 
      - tvheadend
    state: present
 
- name: Start service tvheadend if not started
  service:
    name: tvheadend
    enabled: yes
    state: started
