vars:
  share_path: /mnt/nfsroot

- name: Install nfs packages
  package:
    name: 
      - nfs-kernel-server
    state: present
 
- name: Start service nfs if not started
  service:
    name: nfs-server
    enabled: yes
    state: started
 
 - name: configure exports
      template:
        src: roles/nfs/files/exports.j2
        dest: /etc/exports
      notify: update nfs
      
  handlers:
    - name: update nfs exports
      command: exportfs -a
      listen: update nfs
 
 
 
  tags:
    - nfs
