- name: Install nfs packages
  package:
    name: 
      - nfs-kernel-server
    state: present
 
- name: Start service nfs if not started
  service:
    name: nfs-server
    enabled: yes
    state: started

- name: Create export folder
  file:
    path: "{{ share_path }}"
    state: directory 

- name: configure exports
  #template:
  #  src: ~/ansible/roles/nfs/files/exports.j2
  #  dest: /etc/exports
  #  owner: root
  #  group: root
  #  mode: 0644
  #  become: yes
  #  notify: update nfs
  lineinfile:
    path: /etc/exports
    #insertafter: "# This Line"
    line: "{{ share_path }}(rw,sync,no_root_squash)"
    notify: update nfs
