- name: Install nfs packages
  package:
    name: 
      - nfs-kernel-server
    state: present
 
- name: Start service nfs if not started
  service:
    name: nfs-server
    enabled: yes
    state: started

- name: Create export folder
  file:
    path: "{{ share_path }}"
    state: directory 

- name: configure exports
  template:
    src: roles/nfs/files/exports.j2
    dest: /etc/exports
    notify: update nfs



