
 
- name: Copy over interface config files
  copy:
    src: ~/ansible/roles/internet/files/internet
    dest: /etc/network/interfaces.d/internet
    owner: root
    group: root
    mode: '0644'
  register: interfaceconfigfiles
   
  
- name: Restart service if files changed  
  service:
    name: networking
    enabled: yes
    state: restarted
  when: interfaceconfigfiles.changed
 
 
 
 
 
  tags:
    - internet
