    
    
- name: Install netplan
  netplan_apply: True
  package:
    name: 
      - nplan
      - netplan.io
    state: present
    
     
 
- name: Copy over interface config files
  copy:
    src: ~/ansible/roles/netplan/files/10-eth0-gateway.yaml
    dest: /etc/netplan/10-eth0-gateway.yaml
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['hostname'] == "gateway2"  
  register: interfaceconfigfiles
  notify: netplan generate config
   
   
  
- name: Restart service if files changed  
  service:
    name: networking
    enabled: yes
    state: restarted
  when: interfaceconfigfiles.changed
 
 

 
 
tags:
    - eth0
