- name: Install batman packages
  package:
    name: 
      - batctl
    state: present
 
 
- name: Copy over interface config files
  copy:
    src: ~/ansible/roles/batman-adv/files/batman-adv
    dest: /etc/network/interfaces.d/batman-adv
    owner: root
    group: root
    mode: '0644'
  register: interfaceconfigfiles  
   
  
- name: Copy over dhcp config files
  copy:
    src: ~/ansible/roles/batman-adv/files/dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: '0644'
  register: dhcpconfigfiles  
   
- name: Copy over module config files
  copy:
    src: ~/ansible/roles/batman-adv/files/batman-adv-module.conf
    dest: /etc/modules-load.d/batman-adv-module.conf
    owner: root
    group: root
    mode: '0644'
  register: moduleconfigfiles  
   
  
  
- name: Restart service if files changed  
  service:
    name: networking
    enabled: yes
    state: restarted
  when: interfaceconfigfiles.changed or dhcpconfigfiles.changed or moduleconfigfiles.changed
 
 
 
 
 
  tags:
    - batctl
