- name: Install ntpd packages
  package:
    name: 
      - ntp
    state: present

- name: Copy over config files
  copy:
    src: ~/ansible/roles/ntp-server/files/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  register: configfiles
  
- name: Restart service if files changed  
  service:
    name: ntp
    enabled: yes
    state: restarted
  when: configfiles.changed



- name: Start service ntpd if not started
  service:
    name: ntp
    enabled: yes
    state: started
 
  tags:
    - ntp
