- name: Install mythtv packages
  package:
    name: 
      - mythtv-backend-master
      - mythweb
    state: present
 
- name: Start service mythtv if not started
  service:
    name: mythtv-backend
    enabled: yes
    state: started
 
  tags:
    - mythtv
